//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myshool
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int ld { get; set; }
        public string adminName { get; set; }
        public string adminUser { get; set; }
        public string adminPass { get; set; }
    }
}
