//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myshool
{
    using System;
    using System.Collections.Generic;
    
    public partial class fulldetail
    {
        public int Id { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string nationality { get; set; }
        public string state { get; set; }
        public string localGov { get; set; }
        public System.DateTime dateofBirth { get; set; }
        public byte[] image { get; set; }
        public int examSitting { get; set; }
        public string exam1Name { get; set; }
        public string sub1 { get; set; }
        public string sub12 { get; set; }
        public string sub13 { get; set; }
        public string sub14 { get; set; }
        public string sub15 { get; set; }
        public string exam2Name { get; set; }
        public string sub21 { get; set; }
        public string sub22 { get; set; }
        public string sub23 { get; set; }
        public string sub24 { get; set; }
        public string sub25 { get; set; }
        public int jambScore { get; set; }
        public string jambsub1 { get; set; }
        public string jambsub2 { get; set; }
        public string jambsub3 { get; set; }
        public string jambsub4 { get; set; }
        public string faculty { get; set; }
        public string department { get; set; }
        public string passWord { get; set; }
        public string userName { get; set; }
    }
}
