//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myshool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myschoolEntities3 : DbContext
    {
        public myschoolEntities3()
            : base("name=myschoolEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<faculty> faculties { get; set; }
        public virtual DbSet<grade> grades { get; set; }
        public virtual DbSet<LocalGovernment> LocalGovernments { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<examsitting> examsittings { get; set; }
        public virtual DbSet<nameofexam> nameofexams { get; set; }
        public virtual DbSet<fulldetail> fulldetails { get; set; }
    }
}
